apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend_69
  labels:
    app: guestbook
    tier: frontend_69
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend_69
  template:
    metadata:
      labels:
        tier: frontend_69
    spec:
      containers:
        - name: nginx-69
          image: nginx:1.15
